#!/bin/sh
#SBATCH --time=1:10:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=
#SBATCH --mem=240G
#SBATCH -o log/%x_%j.out
#SBATCH --mail-user=frederic.ouimet.23@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --output=message/%x_%j-result.txt
#SBATCH --error=message/%x_%j-error.txt
module load StdEnv/2023 r/4.3.1
Rscript -e 'batchtools::doJobCollection("/home/fouimet/WishartDensityEstimation/.future/20241013_211830-3xA8mi/doFuture-1_1143165792/jobs/jobf39647f3810e70141ba2e9ad555d0f5c.rds")'
