#!/bin/bash
# A batchtools launch script template for Slurm
#
# Author: Henrik Bengtsson
#SBATCH --job-name=doFuture-1
#SBATCH --output=/home/fouimet/WishartDensityEstimation/.future/20241013_195530-pNXlFr/doFuture-1_1490288339/logs/jobb70ad48b33677e2d7468c97b9c24e57e.log
#SBATCH --nodes=1
#SBATCH --time=00:05:00

#SBATCH --ncpus=63

Rscript -e 'batchtools::doJobCollection("/home/fouimet/WishartDensityEstimation/.future/20241013_195530-pNXlFr/doFuture-1_1490288339/jobs/jobb70ad48b33677e2d7468c97b9c24e57e.rds")'
