#!/bin/bash
#SBATCH --job-name=doFuture-1
#SBATCH --output=/home/fouimet/WishartDensityEstimation/.future/20241013_202545-ugW7jx/doFuture-1_198639927/logs/job0db4c209e35afcb862a29c9255e520e6.log
#SBATCH --error=/home/fouimet/WishartDensityEstimation/.future/20241013_202545-ugW7jx/doFuture-1_198639927/logs/job0db4c209e35afcb862a29c9255e520e6.log
#SBATCH --time=1:10:00
#SBATCH --cpus-per-task=63
#SBATCH --mem=240G
#SBATCH --nodes=2
#SBATCH --partition=compute
module load StdEnv/2023 r/4.3.1
Rscript -e 'batchtools::doJobCollection("/home/fouimet/WishartDensityEstimation/.future/20241013_202545-ugW7jx/doFuture-1_198639927/jobs/job0db4c209e35afcb862a29c9255e520e6.rds")'
